language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install pylint

jobs:
  include:
    - stage: PEP8
      script: pycodestyle --ignore=E402,E501 backend client

    - stage: Pylint
      script: python scripts/kind_lint.py --targets backend client --score 7

notifications:
  slack: rv-027py:bKX55idBpm5OTbuPu9gphYF8
  email: false